export { AmbientBackground, MouseSpotlight } from "./background-effects"
export { SectionHeader } from "./section-header"
export { Hero } from "./hero"
export { About } from "./about"
export { Experience } from "./experience"
export { Projects } from "./projects"
export { Skills } from "./skills"
export { Education } from "./education"
export { Footer } from "./footer"
